version: '3'

services:
  db:
    container_name: posthog_db
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${DB_POSTGRES_DB}
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ${DB_LOCAL_VOLUME}:/var/lib/postgresql/data

  redis:
    container_name: posthog_redis
    image: redis:6-alpine

  web:
    container_name: posthog_web
    image: posthog/posthog:${WEB_VERSION}
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${DB_POSTGRES_USER}:${DB_POSTGRES_PASSWORD}@db:5432/${DB_POSTGRES_DB}
      REDIS_URL: redis://redis:6379/
      SECRET_KEY: ${WEB_SECRET_KEY}
      DISABLE_SECURE_SSL_REDIRECT: 'true'
    links:
      - db:db
      - redis:redis
    ports:
      - 3000:8000
